Token: "10001 qwertyuiop123456asdfghjkl"
SrcFilePath: "/Users/dylan.zan/Documents/github/vsproject/csharp_project/TrafficWizard/srcfile/access.log"
TagetFilePath: "/Users/dylan.zan/Documents/github/vsproject/csharp_project/TrafficWizard/tagetfiles/"