Token: "10001 qwertyuiop123456asdfghjkl"
SrcFilePath: "/Users/dylan.zan/Documents/github/vsproject/csharp_project/TrafficWizard/srcfile/test_src_file.log"
TagetFilePath: "/Users/dylan/Documents/github/vsproject/csharp_project/cs_script/TrafficWizard/tagetfiles/"